### ISSUE TITLE
html generated from readme.md not found

### ISSUE THREAD

**Issue by matheusfelipeog** [davemachado/public-api#31]
It looks like there is a problem building the html from readme.md. The page returns 404:

link: https://api.publicapis.org/
![image](https://user-images.githubusercontent.com/50463866/152114392-b610d273-e327-494c-9733-9fa33d357fdf.png)

**Comment by davemachado** [comment]
Back in business now, thanks for the report. The was a small issue docker image building issue that was excluding the static directory that is now fixed in 989b96684cfee360f6e87602d80225ffee3f6056.
<img width="704" alt="Screen Shot 2022-02-02 at 10 01 45 AM" src="https://user-images.githubusercontent.com/15134885/152179428-8460bcdd-82c4-4497-9c7d-0676a78d29ac.png">
